IntroASP/Models/CRUD_API_RESTContext.cs
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace IntroASP.Models
{
    public partial class CRUD_API_RESTContext : DbContext
    {
        public CRUD_API_RESTContext()
        {
        }

        public CRUD_API_RESTContext(DbContextOptions<CRUD_API_RESTContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Carro> Carros { get; set; } = null!;
        public virtual DbSet<Producto> Productos { get; set; } = null!;

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Server=localhost,1433; User=sa; Password=myFirst8DbSqlExpress; Database=CRUD_API_REST; Trusted_Connection=false;");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Carro>(entity =>
            {
                entity.Property(e => e.Year);
                    

                entity.Property(e => e.Color)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.Marca)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Modelo)
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Producto>(entity =>
            {
                entity.Property(e => e.Descripcion)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.Nombre)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Precio).HasColumnType("decimal(12, 2)");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}

IntroASP/Models/Carro.cs
using System;
using System.Collections.Generic;

namespace IntroASP.Models
{
    public partial class Carro
    {
        public int Id { get; set; }
        public string? Marca { get; set; }
        public string? Modelo { get; set; }
        public int? Year { get; set; }
        public string? Color { get; set; }
    }
}

IntroASP/Models/ErrorViewModel.cs
namespace IntroASP.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

IntroASP/Models/Producto.cs
using System;
using System.Collections.Generic;

namespace IntroASP.Models
{
    public partial class Producto
    {
        public int Id { get; set; }
        public string? Nombre { get; set; }
        public decimal? Precio { get; set; }
        public int? Cantidad { get; set; }
        public string? Descripcion { get; set; }
        public DateTime? FechaCreacion { get; set; }
    }
}

IntroASP/Models/ViewsModels/CarroViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace IntroASP.Models.ViewsModels
{
    public class CarroViewModel
    {
        [Required]
        [Display(Name = "ID:")]
        public int Id { get; set; }

        [Required]
        [Display(Name = "Marca:")]
        public string Marca { get; set; }

        [Required]
        [Display(Name = "Modelo:")]
        public string Modelo { get; set; }

        [Required]
        [Display(Name = "Año:")]
        public string Year { get; set; }


        [Required]
        [Display(Name = "Color:")]
        public string Color { get; set; }
    }
}

IntroASP/Controllers/ApiCarController.cs
using IntroASP.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace IntroASP.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class ApiCarController : ControllerBase
    {

        private readonly CRUD_API_RESTContext _restContext;

        public ApiCarController(CRUD_API_RESTContext _restContext)
        {
            this._restContext = _restContext;
        }

        public async Task<List<Carro>> Get()
            => await _restContext.Carros.ToListAsync();
    }
}

IntroASP/Controllers/BrandController.cs
using IntroASP.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace IntroASP.Controllers
{
    public class BrandController : Controller
    {
        private readonly CRUD_API_RESTContext _restContext;

        public BrandController(CRUD_API_RESTContext restContext)
        {
            _restContext = restContext;
        }
        public async Task<IActionResult> Index()
            => View(await _restContext.Productos.ToListAsync());
        
    }
}

IntroASP/Controllers/CarrosController.cs
using IntroASP.Models;
using IntroASP.Models.ViewsModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace IntroASP.Controllers
{
    public class CarrosController : Controller
    {
        private readonly CRUD_API_RESTContext _restContext;

        public CarrosController (CRUD_API_RESTContext restContext)
        {
            _restContext = restContext;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _restContext.Carros.ToListAsync());
        }
            
       

        public IActionResult Create()
        {
            
            ViewData["Colors"] = new SelectList(_restContext.Carros, "Color", "Color");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CarroViewModel model)
        {
            if (ModelState.IsValid)
            {
                var car = new Carro()
                {
                    Id = model.Id,
                    Marca = model.Marca,
                    Modelo = model.Modelo,
                    Year = int.Parse(model.Year),
                    Color = model.Color,
                };

                _restContext.Add(car);
                await _restContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Colors"] = new SelectList(_restContext.Carros, "Color", "Color", model.Color);
            return View(model);
        }
    }
}

IntroASP/Controllers/HomeController.cs
using IntroASP.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace IntroASP.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

IntroASP/Views/Brand/Index.cshtml
@model List<Producto>

<h1>Productos</h1>

<table class="table">
    <thead>
        <tr>
            <th>Nombre</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var brand in Model)
        {
            <tr>
                <td>@Html.DisplayFor(m => brand.Nombre)</td>
            </tr>
        }
    </tbody>

</table>

IntroASP/Views/Carros/Create.cshtml
@using IntroASP.Models.ViewsModels
@model CarroViewModel

<h1>Crear Carros</h1>

<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="pb-3">

                <div class="form-group pb-1">
                    <label asp-for="Id" class="control-label"></label>
                    <input asp-for="Id" class="form-control" />
                    <span asp-validation-for="Id" class="text-danger"></span>
                </div>

                <div class="form-group pb-1">
                    <label asp-for="Marca" class="control-label"></label>
                    <input asp-for="Marca" class="form-control" />
                    <span asp-validation-for="Marca" class="text-danger"></span>
                </div>
                

                <div class="form-group" pb-1>
                <label asp-for="Modelo" class="control-label"></label>
                    <input asp-for="Modelo" class="form-control" />
                <span asp-validation-for="Modelo" class="text-danger"></span>
            </div>

                <div class="form-group" pb-1>
                    <label asp-for="Year" class="control-label"></label>
                    <input asp-for="Year" class="form-control" />
                    <span asp-validation-for="Year" class="text-danger"></span>
                </div>

                <div class="form-group" pb-1>
                    <label asp-for="Color" class="control-label"></label>
                    <select asp-for="Color" class="form-control" asp-items="ViewBag.Colors"></select>
                    <span asp-validation-for="Color" class="text-danger"></span>
                </div>

            </div>

            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

IntroASP/Views/Carros/Index.cshtml
@model List<Carro>

<h1>Carros</h1>

<p>
    <a asp-action="Create">Crear</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>Marca</th>
            <th>Modelo</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var car in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(m => car.Marca)
                </td>
                <td>
                    @Html.DisplayFor(m => car.Modelo)
                </td>
                <td>
                    ok
                </td>
            </tr>
        }
    </tbody>
</table>

IntroASP/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

IntroASP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IntroASP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/IntroASP.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">IntroASP</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Brand" asp-action="Index">Marca</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Carros" asp-action="Index">Carros</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - IntroASP - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>